SNP-SELEX:
  FILE_URLS:
    BATCH_1: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE118nnn/GSE118725/suppl/GSE118725%5Fpbs.obs%5Fpval05.tsv.gz
    BATCH_2: https://ftp.ncbi.nlm.nih.gov/geo/series/GSE118nnn/GSE118725/suppl/GSE118725%5Fpbs.novel%5Fbatch.tsv.gz

TFBS-SCAN:
  # Target JASPAR profiles to scan against
  TARGETS:
    - AR|MA0007.3|17
    - ARNTL|MA0603.1|10

GENOME:
  # Genome build
  BUILDS:
    - hg19
  # Genome host
  SOURCE: UCSC
  # Regex filtering - filter FASTA to main chromosomes
  FILTER: chr[0-9XY]+$
  # Target installation directory
  OUTDIR: resources/data/genome
  # Blacklist URLs
  BLACKLIST_HG19: https://github.com/Boyle-Lab/Blacklist/raw/master/lists/hg19-blacklist.v2.bed.gz
  BLACKLIST_HG38: https://github.com/Boyle-Lab/Blacklist/raw/master/lists/hg38-blacklist.v2.bed.gz
